server:
  port: 8080

logging:
  level:
    com.netflix.discovery: error

zuul:
#  PreDecorationFilter.pre.disable: true
#  RibbonRoutingFilter.route.disable: true
  retryable: true
#  ignored-services: '*'
  prefix: /api
  strip-prefix: true
  servlet-path: /zuul
  add-host-header: true
  routes:
    spring-simple-service:
      serviceId: spring-simple-service
      path: /simple/**
      sensitiveHeaders: testSensitive,Cookie,Set-Cookie,Authorization
    spring-simple-service2:
      url: http://localhost:8082
      path: /simple2/**
    spring-simple-service3:
      path: /simple3/**
      url: forward:/internal

spring-simple-service:
  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
  ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 5000

br.com.gateway:
  custom-headers:
    gateway-name: Zuul
    host-name: localhost
  fallback:
    spring-simple-service:
      service-id: spring-hystrix-service
#      url: http://localhost:8081/